project:
  type: book

book:
  title: "AI Genomics Workflow Tutorial"
  author: "Gina M. Gehling & Lacey W. Heinsberg"
  date: last-modified
  date-format: "YYYY"
  chapters:
    - index.qmd
    - part: "Tutorial"
      chapters:
        - tutorial_overview.qmd
        - tutorial_code_of_conduct.qmd
        - tutorial_application.qmd
        - tutorial_disclosure.qmd
format:
  html:
    theme: cosmo
    highlight-style: tango
    toc: true
    code-fold: show
    number-sections: false

